[package]
name = "sahyadri-smt"
description = "Sahyadri sparse merkle tree for account state commitment"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
p3-field = { git = "https://github.com/0xPolygonZero/plonky3", branch = "main" }
p3-goldilocks = { git = "https://github.com/0xPolygonZero/plonky3", branch = "main" }
p3-symmetric = { git = "https://github.com/0xPolygonZero/plonky3", branch = "main" }
rand = "0.9"

[lints]
workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
bincode = "1.3"
sha3 = "0.10"

[[bench]]
name = "sync_wave_bench"
harness = false
