#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "Sahyadri WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sahyadri-keygen ./build/docs/sahyadri-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "Sahyadri WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sahyadri-rpc ./build/docs/sahyadri-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "Sahyadri WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sahyadri-core ./build/docs/sahyadri-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "Sahyadri WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sahyadri ./build/docs/sahyadri.ts
else
    echo "building keygen"
    typedoc --name "Sahyadri WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sahyadri-keygen ./build/docs/sahyadri-keygen.ts
    echo "building rpc"
    typedoc --name "Sahyadri WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sahyadri-rpc ./build/docs/sahyadri-rpc.ts
    echo "building core"
    typedoc --name "Sahyadri WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sahyadri-core ./build/docs/sahyadri-core.ts
    echo "building full"
    typedoc --name "Sahyadri WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/sahyadri ./build/docs/sahyadri.ts

fi